### ISSUE TITLE
Add package.json and publish to npm

### ISSUE THREAD

**Issue by rickerd** [tristandenyer/clone-section-of-form-ES6-or-jQuery#22]
It will be great if you could publish this on npm. Then everyone can download it via npm/yarn with nice versions and stuff.

**Comment by tristandenyer** [comment]
Thanks for the suggestion! Will be working on that shortly.

**Comment by tristandenyer** [comment]
@rickerd I just published to npm (https://www.npmjs.com/package/@tristandenyer/clone-form) under the `-alpha` flag. Feel free to test and let me know how it works for you.
